"""init database

Revision ID: 5abd11a78a11
Revises: 
Create Date: 2025-12-26 01:11:50.440642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5abd11a78a11'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_post_id'), table_name='post')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('post_id_seq'::regclass)"), autoincrement=True, nullable=False, comment='Unique identifier of the post'),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='Title of the post'),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Content of the post'),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Publication status of the post'),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=True, comment='Rating of the post'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.UUID(), autoincrement=False, nullable=False, comment='Identifier of the user who created the post'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='post_owner_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_post_id'), 'post', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False, comment='Unique identifier of the user'),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Email address of the user'),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False, comment='Hashed password of the user'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('votes',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False, comment='Identifier of the user who voted'),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Identifier of the post that was voted on'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name=op.f('votes_post_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('votes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name=op.f('votes_pkey'))
    )
    # ### end Alembic commands ###
